import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c8c6c6",
        "outline-variant": "#d0c6ae",
        "on-secondary-container": "#725b00",
        "surface-container-high": "#e8e8e8",
        "on-primary-container": "#5f5e5e",
        "on-primary-fixed": "#1b1c1c",
        "on-tertiary-container": "#5f5f5e",
        "on-secondary-fixed-variant": "#574500",
        "surface-tint": "#5f5e5e",
        "primary-fixed": "#e5e2e1",
        "primary": "#5f5e5e",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "on-primary": "#ffffff",
        "secondary": "#735c00",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-highest": "#e2e2e2",
        "primary-container": "#dbd9d8",
        "surface-container": "#eeeeee",
        "primary-fixed-dim": "#c8c6c5",
        "surface": "#f9f9f9",
        "surface-container-low": "#f3f3f3",
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed": "#241a00",
        "on-tertiary-fixed": "#1b1c1c",
        "outline": "#7f7662",
        "on-secondary": "#ffffff",
        "tertiary-fixed": "#e4e2e1",
        "on-primary-fixed-variant": "#474746",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ebc23e",
        "inverse-primary": "#c8c6c5",
        "tertiary": "#5f5e5e",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed": "#ffe087",
        "background": "#f9f9f9",
        "error": "#ba1a1a",
        "surface-dim": "#dadada",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f1f1f1",
        "on-surface-variant": "#4d4634",
        "inverse-surface": "#2f3131",
        "on-background": "#1a1c1c",
        "secondary-container": "#fdd34d",
        "tertiary-container": "#dbd9d9",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        sans: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
  plugins: [],
};
export default config;
